### ISSUE TITLE
Immutable.js rendering.

### ISSUE THREAD

**Issue by j-pb** [skortchmark9/reselect-tools#11]
Hey,
The redux-tools natively support rendering Immutable.js data structures,
it would be really nice if reselect-tools could do the same.
I could work it out and create a pull request, if you're interested?

Cheers,
jp

**Comment by skortchmark9** [comment]
Sure, I'd be happy to take a PR. I'm guessing you'd need to serialize it on the application side before you call ```selectorGraph()```

**Comment by skortchmark9** [comment]
@XuluWarrior added a pull in the extension that I think I'll take instead. See: https://github.com/skortchmark9/reselect-devtools-extension/issues/3
