### ISSUE TITLE
reselect-tools not receiving dependencies

### ISSUE THREAD

**Issue by trentfridey** [skortchmark9/reselect-tools#14]
Hi, thanks for making this! I have implemented reselect-tools in my app, and I have the Chrome extension. The nodes are showing up, but the dependency graph is not being drawn.

I pulled up the demo app you have on the repo, and it seems the same thing is happening. It seems that reselect-tools is looking for the selector dependencies to be returned from reselect but `selector.dependencies` always returns `undefined`.

**Comment by trentfridey** [comment]
Looks like this is due to apps using reselect v3 instead of v4. Updating to `reselect@4.0.0` on my end fixed this. Your deployed demo page is still using `reselect@3.0.1`. I would offer a pull request but the code is already updated in demo.html in the repo. You just need to redeploy it.

**Comment by skortchmark9** [comment]
Ah, you're correct. Thanks for pointing that out! I've fixed it now. 

As of reselect 4.0 selectors own their own dependencies, so `reselect-tools` no longer needs to manage them for you. Unfortunately that means if you use the new version of `reselect-tools` with the old version of `reselect`, you won't see dependencies.
