### ISSUE TITLE
`ReselectTools.registerSelectors()` fails if the given object has a null value property

### ISSUE THREAD

**Issue by javierfernandes** [skortchmark9/reselect-tools#27]
Hi !

I was starting to use the tool, and followed the setup code like this

in my storeCreator.js (setups the store)
```
import * as selectors from 'selectors/selectors'

ReselectTools.getStateWith(() => store.getState())
ReselectTools.registerSelectors(selectors)
```

And I was getting this exception

![image](https://user-images.githubusercontent.com/4428120/34778859-4f92b6d0-f5fd-11e7-8fb9-24b681326f14.png)

My selectors file seems a regular file

```
export { selectedObject, selectedObjects } from './objects'
export { vmLoading, vmLoaded, tasksComply } from './project'
```

I started to inspect the "selectors" object (from import * as selectors) and noticed that it has a couple of extra fields set by babel or whatever the underlying impl of the es modules creates.
And seems like one of those fields was null and made the library break.

I solved it by filtering some properties like this

```js
    const distilledSelectors = Object.keys(selectors).reduce((acc, k) => {
      const v = selectors[k]
      if (v) acc[k] = v
      return acc
    }, {})
    ReselectTools.registerSelectors(distilledSelectors)
```

But maybe it would be great if the library already fixes this by checking for "selector" to be truthy.

Thanks !

**Comment by skortchmark9** [comment]
Moving all extension issues into the main repo, per #24
