### ISSUE TITLE
Support Immutable values

### ISSUE THREAD

**Issue by XuluWarrior** [skortchmark9/reselect-tools#28]
Currently, if a selector outputs Immutable values these are shown in the state tree in their rawest object form e.g. `Immutable.Map({a:1})` becomes
```
{
  size : 1
 __altered : false
 _root:
  entries : [
   "a"
  ]
  ownerID: {}
}
```
rather than
```
{
  a : 1
}
```

**Comment by skortchmark9** [comment]
Moving all extension issues into the main repo, per #24
