### ISSUE TITLE
Graph is incorrect. There are no arrows on the graph.

### ISSUE THREAD

**Issue by rkarakulov** [skortchmark9/reselect-tools#29]
1. I installed reselect-devtools-extension
2. Open demo page http://skortchmark.com/reselect-tools/examples/demo.html
3. Graph displays only points, no relationships 
![image](https://user-images.githubusercontent.com/3773028/49577545-44192a80-f950-11e8-91c3-bd55bc585774.png)

**Comment by skortchmark9** [comment]
Moving all extension issues into the main repo, per #24
