### ISSUE TITLE
TypeScript type definitions for reselect-tools

### ISSUE THREAD

**Issue by aziz** [skortchmark9/reselect-tools#3]
It would be really nice if you provide these definitions since reselect already does this

**Comment by skortchmark9** [comment]
Wow, my first issue! Thanks! I haven't used typescript too much before, so can you tell me how this would help you? Is this because createSelectorWithDependencies is uninferable?

**Comment by aziz** [comment]
Yes and all the other APIs should have types to be inferable.
if you wrap most of the methods from `reselect` maybe you can reuse a lot from [this file](https://github.com/reactjs/reselect/blob/master/src/index.d.ts)

Great Job BTW 👍

**Comment by skortchmark9** [comment]
Realistically I'm not going to do this since I don't use typescript myself. I'd be happy to accept a PR though. Until then, I'm going to close this down.
