### ISSUE TITLE
Request to update repository with version 0.0.2 from Chrome App Store

### ISSUE THREAD

**Issue by hydrosquall** [skortchmark9/reselect-tools#30]
Hi @skortchmark9 ,

Thanks for the great work on this extension! I was wondering if you might be able to upload the source of the `v0.0.2` version of this extension to Github, which has some functionality that isn't in `v0.0.1`, like enabling highlighting of the most recomputed nodes, or counting the number of recomputations. (very useful features, by the way!)

I'm experimenting with some different graph layouts, and was hoping to work with the same version of the source code that's in the chrome extension store.

Thanks for your consideration!

**Comment by skortchmark9** [comment]
Moving all extension issues into the main repo, per #24
