### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by trungdq88** [skortchmark9/reselect-tools#5]
...for creating this awesome project. I would buy you a beer 👍

**Comment by skortchmark9** [comment]
Awwww how nice! Are you using it in your app? Did you solve any problems with it?

**Comment by skortchmark9** [comment]
Wow so helpful! Thanks dude! These are all really great ideas. I'd take a PR for basically any of them - I don't have a contribution guide but I'd be down to do a code review. I'd just ask that:
* you keep the test coverage about where it is
* update the README to document any new features/api you add.

I thought quite a bit about 4.) and I couldn't think of a good way to do it that would work in a minified / uglified build. If you're not minifying, then you can get pretty far doing introspection on the function name, or on the names of the arguments of a descendant selector.

**Comment by skortchmark9** [comment]
Of these four, I think the most necessary improvement is the exception handling in selectorGraph(). I've definitely seen selector exceptions be swallowed before in unpleasant ways and it would be great to expose them better. I'll break off a new issue for that, but I'm going to close this one down.
