### ISSUE TITLE
Question: running in development versus production

### ISSUE THREAD

**Issue by andrew-codes** [skortchmark9/reselect-tools#8]
Good morning. First and foremost, thank you for the great work on this tool! I have only started using it, but already it has been a great help in getting our selector optimizations underway.

From the examples provided, it seems the reselect-tools would be run in both development and production. Have you noticed a perceivable performance impact of running this in production? Or are the examples more for simplicity and we should configure our app in some way to only run this tool in development? If we should only run this in development, I am happy to submit a PR to the docs with some ways to accomplish this or if you have thoughts on how it would best be handled.

Again, thanks for all the hard work!

**Comment by skortchmark9** [comment]
Hey Andrew - my goal was to make it usable both in development and production - unless you're noticing performance issues you should be good. Let me know if you find something slowing your app down.

**Comment by skortchmark9** [comment]
@andrew-codes let me know if there's anything to do here, but I'm closing for now.

**Comment by skortchmark9** [comment]
Also, there's this possibility: https://github.com/skortchmark9/reselect-tools/issues/20
