### ISSUE TITLE
NPM version out of date

### ISSUE THREAD

**Issue by austinfox** [skortchmark9/reselect-tools#9]
Thanks a ton for creating this! Would you mind updating the module to a new version on npmjs? The only version there is quite out of date and does not work with the instructions provided by the github README.

**Comment by skortchmark9** [comment]
Hey there @austinfox  - I'm not sure what you mean?

[NPM lists version 0.0.6](https://www.npmjs.com/package/reselect-tools), and that's the most recent version.

What's the issue you're having with the instructions?
